### ISSUE TITLE
Generator does not update code

### ISSUE THREAD

**Issue by yoavrofe** [TeamWanari/rosetta#19]
Generator does not update code after changing the JSON files and running `flutter packages pub run build_runner build` (mac, flutter master channel).

Running `flutter clean` solves the problem, but this has to be run each time.

**Comment by agta1991** [comment]
After further investigation on the currently used Builder logic, we found that it only detects .dart file changes.

For proper functioning we need to refactor the Builder logic with a custom builder, which depend on both the referenced .json files and .dart files.

**Comment by agta1991** [comment]
v0.1.1 release fixes this issue.
