### ISSUE TITLE
Support latest Dart 2.10 and Flutter 1.22

### ISSUE THREAD

**Issue by talamaska** [TeamWanari/rosetta#58]
new versions of almost everything, build_runner , build, analyzer, I have conflicts with other generators dependencies.

**Comment by RenatoKiss** [comment]
Changes merged into stable

**Comment by talamaska** [comment]
@RenatoKiss maybe you should mark the build as null safe? I saw some changes related to that. Or it's nothing? We will definetly need a nullsafe version if this isn't I haven't tried.

**Comment by RenatoKiss** [comment]
@talamaska These changes were not related to null safety, but we are working on it.
I made an issue #62 if you want to follow updates about it.
