### ISSUE TITLE
0.2.2 does not compile

### ISSUE THREAD

**Issue by noordawod** [TeamWanari/rosetta#68]
The current version does not compile when nullsafety is engaged.

The reason is that `pubspec.yaml` broadcasts dependency on Dart 2.10+ which has nullsafety ON by default. In comparison, the previous version 0.2.0 relied on Dart 2.6.0 which had nullsafety but it was OFF by default.

To fix, merely update the version back to 2.6.0 and everything works.

I can submit a pr to update this and publish a 0.2.3 of Rosetta and its generator. What do you say?

**Comment by l4ty4k** [comment]
Yeah, this was an error on our side. We'd appreciate the PR, so please submit it. 

We already working on migrating the project to null_safety, but one of the dev dependency (build_runner) is yet to migrate. So as soon as possible we will release a null_safe version.

**Comment by noordawod** [comment]
Here you go: https://github.com/TeamWanari/rosetta/pull/69

**Comment by noordawod** [comment]
Thanks for the quick merge!
